export const OFFSHORE_MOCK_DATA = [
  {
    category: "Worldwide Credit Card Acquiring: Gaming (3DS)",
    categoryNote: "Note: 1) Acquiring Banks for Trusted: Spain, UK, Bulgaria 2) Acquiring Banks for FTDs: Kenya, Nigeria",
    channelCode: "USDTPTO-1001",
    payIn: "6.00% - up to $1M\n5.75% - up to $5M\n5.50% - up to $10M\n5.25% - 10M+",
    setupFee: "No Set-Up Fee",
    annualFee: "No Annual Fee",
    otherFees: "No Hidden Fees",
    rollingReserve: "10% - 180 Days ($100K Cap) if Whitelisted Traffic",
    cbFee: "$45 USD",
    refundFee: "$10 USD",
    transactionFees: "$0.45",
    settlementUsdt: "1.75% Min: $10k USDT",
    transactionMinMax: "$10/$2,000",
    settlementCycle: "T+7 Billing Period: Weekly",
    velocitiesLimits: "4 per day / 20 per month on declines.",
    whitelistFtdTrusted: "FTD is allowed if no more than 50% of TPV",
    processingCurrency: "Trusted traffic: USD, EUR, AUD, CAD and GBP available",
    geoOpenForProcessing: "ALL except OFAC, India, Pakistan, Nepal, Sri Lanka & Bangladesh & USA",
    mccCodes: "Dynamic MCC Codes",
    mid3dsOr2d: "3D",
    descriptor: "Dynamic Descriptors",
    acceptanceRate: "60% - 70%",
    integrationType: "Direct (S2S)",
    pageSlug: "direct"
  },
  {
    category: "Worldwide Credit Card Acquiring: Forex (3DS)",
    categoryNote: "NOTE: Acquiring Bank Locations: Spain, UK, Bulgaria",
    channelCode: "USDTPTO-1004",
    payIn: "6.00% - up to $1M\n5.75% - up to $5M\n5.50% - up to $10M\n5.25% - 10M+",
    setupFee: "No Set-Up Fee",
    annualFee: "No Annual Fee",
    otherFees: "No Hidden Fees",
    rollingReserve: "10% - 180 Days ($100K Cap) if Whitelisted Traffic",
    cbFee: "$45 USD",
    refundFee: "$10 USD",
    transactionFees: "$0.45",
    settlementUsdt: "1.75% Min: $10k USDT",
    transactionMinMax: "$10/$2,000",
    settlementCycle: "T+7 Billing Period: Weekly",
    velocitiesLimits: "4 per day / 20 per month on declines.",
    whitelistFtdTrusted: "Trusted Only - No FTDs",
    processingCurrency: "Trusted traffic: USD, EUR, AUD, CAD and GBP available",
    geoOpenForProcessing: "ALL except OFAC, India, Pakistan, Nepal, Sri Lanka & Bangladesh & USA",
    mccCodes: "Dynamic MCC Codes",
    mid3dsOr2d: "3D",
    descriptor: "Dynamic Descriptors",
    acceptanceRate: "75%",
    integrationType: "Direct (S2S)",
    pageSlug: "direct"
  },
  {
    category: "Credit Card Acquiring: 2D",
    categoryNote: "NOTE: Acquiring Bank Locations: UK and Cambodia",
    channelCode: "USDTPTO-1005",
    payIn: "6.00% - up to $1M\n5.75% - up to $5M\n5.50% - up to $10M\n5.25% - 10M+",
    setupFee: "No Set-Up Fee",
    annualFee: "No Annual Fee",
    otherFees: "No Hidden Fees",
    rollingReserve: "10% - 180 Days ($100K Cap) if Whitelisted Traffic",
    cbFee: "$45 USD",
    refundFee: "$10 USD",
    transactionFees: "$0.45",
    settlementUsdt: "1.75% Min: $10k USDT",
    transactionMinMax: "$10/$2,000",
    settlementCycle: "T+7 Billing Period: Weekly",
    velocitiesLimits: "4 per day / 20 per month on declines.",
    whitelistFtdTrusted: "Whitelist: ONLY",
    processingCurrency: "MXN (FX variable almost Nil to USD)",
    geoOpenForProcessing: "US",
    mccCodes: "Dynamic MCC Codes",
    mid3dsOr2d: "2D",
    descriptor: "Dynamic Descriptors",
    acceptanceRate: "80%+",
    integrationType: "Direct (S2S)",
    pageSlug: "direct"
  }
]
